baseurl = "http://hugo.spf13.com/"
languageCode = "en-us"
title = "Hugo Future Imperfect"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 3
disqusShortname = "shortname"
googleAnalytics = ""
pluralizeListTitles = false

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "HTML5 UP theme, Future Imperfect with some extra goodies, ported by Julio Pescador. Powered by Hugo"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Future Imperfect"
    # set this to the section name if section is not post
    viewMorePostLink     = "/blog/"

# Optional Params
    # This will match the navbarTitle to the section of the website
    dynamicTitles        = true
    # RSS icon that appear on the sidebar, next to the social media buttons
    rssAppearAtTop       = true
    rssAppearAtBottom    = true
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""

    # Disable showing the social sharing links on blog posts
    socialShareDisabled = false

    # Load custom CSS or JavaScript files. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    customCSS            = ["default"]
    customJS             = ["default"]

# Disqus will take priority over staticman due to its ease of use. Feel free to check out both and decide.
[params.staticman]
    staticman = false
    username  = ""
    repo      = ""
    branch    = ""

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Hugo Future Imperfect"

    paragraph = "Another fine responsive site template by <a href=\"http://html5up.net\">HTML5 UP</a>. Ported by Julio Pescador with some extra goodies <i class='fa fa-hand-peace-o'></i>"

    about     = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tellus lacus, auctor vehicula molestie quis, tempor quis velit. Quisque in quam ac leo efficitur vulputate. Phasellus ullamcorper aliquam sodales. Maecenas sit amet condimentum ipsum. Proin sit amet ligula elit. Mauris."

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/main/logo.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = true
    width     = ""
    alt       = "Hugo Future Imperfect"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 2

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text

[[menu.main]]
    name = "Home"
    url = "/"
    identifier = "fa fa-home"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    identifier = "fa fa-id-card-o"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    identifier = "fa fa-newspaper-o"
    weight = 3

[[menu.main]]
    name = "Itemized"
    url = "/itemized/"
    identifier = "fa fa-list"
    weight = 4

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    identifier = "fa fa-sitemap"
    weight = 5

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    identifier = "fa fa-envelope-o"
    weight = 6

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "jpescador"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "julio_pescador"
    email           = ""
